config/routes.rb
Rails.application.routes.draw do

  root 'sales#index'

  #root 'statistics#index'
  get 'statistics/index'
  resources :homes
  resources :charts, only: [] do
    collection do
      get 'sporters_by_age'
      get 'sporters_by_country'
      get 'results_by_country'
      get 'competition_by_year'
      get 'chart_by_tenpo_code'
    end
  end
  get 'statistics/search' => 'statistics#search'
  get 'sales/search' => 'sales#search'
end

app/models/competition.rb
class Competition < ActiveRecord::Base
	has_many :competition_results
end

app/models/competition_result.rb
class CompetitionResult < ActiveRecord::Base
  belongs_to :sporter
  belongs_to :competition
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :sporters
end

app/models/profit_loss.rb
class ProfitLoss < ActiveRecord::Base
end

app/models/sale.rb
class Sale < ActiveRecord::Base
end

app/models/sporter.rb
class Sporter < ActiveRecord::Base
  belongs_to :country
  has_many :competition_results
end

app/models/visit.rb
class Visit < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  
  #Display sporters by age
  def sporters_by_age
  	result = Sporter.group(:age).count
    render json: [{name: 'Count', data: result}]
  end

  #display how many sporters each country has
  def sporters_by_country
  	result = { }
  	Country.all.map do |c|
  		result[c.name] = c.sporters.count
  	end
  	render json: [{name: 'Count', data: result}]
  end

  #display how many times each country took a certain place
  def results_by_country
  	result = Country.all.map do |c|
  		places = { }
  		(1..6).each do |place|
  			places[place] = c.sporters.joins(:competition_results).where("competition_results.place = #{place}").count
  		end
  		{
  			name: c.name,
  			data: places
  		}
  	end
  	render json: result
  end

  #display how many competitions were held each year.
  def competition_by_year
  	result = CompetitionResult.group_by_year(:created_at, format: '%Y').count
  	render json: [{ name: 'Count', data: result}]
  end

  def chart_by_tenpo_code
    sale_by_month = Sale.where('tenpo = ?', params[:tenpo_code].to_i).group(:sale_month).sum(:uriage)
    profit_by_month = ProfitLoss.where('tenpo = ?', params[:tenpo_code].to_i).group(:pl_month).sum(:rieki)
    res_by_month = { }
    sale_by_month.zip(profit_by_month).each do |s,p|
      if(s[1] != 0)
       res_by_month[s[0]] = (p[1]/s[1]*100).to_f.round(2)
      else
        res_by_month[s[0]] = 0
      end
    end
     sale_by_year = Sale.group(:sale_month).sum(:uriage)
     profit_by_year = ProfitLoss.group(:pl_month).sum(:rieki)
     res_by_year = { }
     sale_by_year.zip(profit_by_year).each do |s,p|
      if(s[1] != 0)
       res_by_year[s[0]] = (p[1]/s[1]*100).to_f.round(2)
      else
        res_by_year[s[0]] = 0
      end
    end
    #results = {}
    #res.each { |k,v| results[k] = v }

    default = [{ name: '店舗', data: res_by_month},{name: '全社', data: res_by_year}]
    render json: default  
=begin
[{
       name: "validation line",
       data:[ 
          ["2015-09-30",166,nil,nil], # no annotations
          ["2015-10-15",242,"Test Starts","point { ...}"] # with annotatiosn and style
       ], 
       types:[ "annotation", "style" ] # new: optional define additionals column roles
    }]
=end

  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
      @visits = Visit.all
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def index
  end
  
  def search
  	@abc = [1,2,3,4,5,6,4,5,8,7,9,4,56,1]
  	sale_by_month = Sale.where('tenpo = ?', params[:tenpo_code].to_i).group(:sale_month).sum(:uriage).sort
    profit_by_month = ProfitLoss.where('tenpo = ?', params[:tenpo_code].to_i).group(:pl_month).sum(:rieki).sort
    @month = Array.new
    sale_by_month.each_with_index do |s, index|
       @month[index] = s[0]
       # use key, value and index as desired
    end
    @month_profit = Array.new
    profit_by_month.each_with_index do |p, i|
    	@month_profit[i] = p[1].to_i
    end
     
    @sale_per = Array.new
    res = { }
    sale_by_month.zip(profit_by_month).each do |s,p,index|
    	if(s[1] != 0)
        res[s[0]] = (p[1]/s[1]*100).to_f.round(2)
      else
        res[s[0]] = 0
      end
    end
    res.each_with_index do |r,index|
    	   @sale_per[index] = r[1]
    end 

    @year_profit = Array.new
    sale_by_year = Sale.group(:sale_month).sum(:uriage).sort
    profit_by_year = ProfitLoss.group(:pl_month).sum(:rieki).sort
    res_by_year = { }
    sale_by_year.zip(profit_by_year).each do |s,p|
      if(s[1] != 0)
        res_by_year[s[0]] = (p[1]/s[1]*100).to_f.round(2)
      else
        res_by_year[s[0]] = 0
      end
    end
    res_by_year.each_with_index do |r,index|
      @year_profit[index] = r[1]
    end
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def index
  	
  end
  def search

  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
	def get_sale_data(tenpo_code)
		@sale = Sale.where('tenpo = ?', params[:tenpo_code].to_i).group(:sale_month).sum(:uriage)
	end

	def get_profite_data(tenpo_code)
		@profit = ProfitLoss.where('tenpo = ?', params[:tenpo_code].to_i).group(:pl_month).sum(:rieki)
	end
   
	def chart_by_tenpo_code(tenpo_code)
		line_chart chart_by_tenpo_code_charts_path(tenpo_code: tenpo_code),discrete: true, height: '500px', library: {
		  		yAxis: {
		  			title: {
		  				text: 'Sale'
		  			}
		  		},
		  		xAxis: {
		  			title: {
		  				text: 'Month'
		  			}
		  		},
		  		legend: {
		            layout: 'horizontal',
		            align: 'center',
		            verticalAlign: 'top',
		            floating: true
		        }
		 }
	end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
  def sporters_by_age
    bar_chart sporters_by_age_charts_path, height: '500px', library: {
      title: {text: 'Sporters by age', x: -20},
      yAxis: {
         allowDecimals: false,
         title: {
             text: 'Ages count'
         }
      },
      xAxis: {
         title: {
             text: 'Age'
         }
      }
    }
  end

  def sporters_by_country
  	column_chart sporters_by_country_charts_path, height: '500px', library: {
  		title: { text: 'Sporters By Country'},
  		yAxis: {
  			allowDecimals: false,
  			title: {
  				text: 'Sporters Count'
  			}
  		},
  		xAxis: {
  			title: {
  				text: 'Country'
  			}
  		}
  	}
  end

  def results_by_country
  	column_chart results_by_country_charts_path, stacked: true, height: '500px', library: {
  		title: { text: 'Results By Countries' },
  		yAxis: {
  			allowDecimals: false,
  			title: {
  				text: 'Count'
  			}
  		},
  		xAxis:{
  			title: {
  				text: 'Countries By Place'
  			}
  		}
  	}
  end

  def competition_by_year
  	line_chart competition_by_year_charts_path, height: '500px', library: {
  		title: { text: 'Competition by year'},
  		yAxis: {
  			allowDecimals: false,
  			title: {
  				text: 'Competitions Count'
  			}
  		},
  		xAxis: {
  			title: {
  				text: 'Year'
  			}
  		}
  	}
  end
end

app/views/homes/create.html.erb
<h1>Homes#create</h1>
<p>Find me in app/views/homes/create.html.erb</p>

app/views/homes/destroy.html.erb
<h1>Homes#destroy</h1>
<p>Find me in app/views/homes/destroy.html.erb</p>

app/views/homes/edit.html.erb
<h1>Homes#edit</h1>
<p>Find me in app/views/homes/edit.html.erb</p>

app/views/homes/index.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-6">
		<h3 class="text-center">Visits By Day</h3>
		<!-- line chart - Single Series -->
		<!-- showing the number of vists by day. -->
		<%= line_chart @visits.group_by_day(:visited_at).count, descrete: true %>	
	</div>
	<div class="col-xs-12 col-sm-12 col-md-6">
		<h3 class="text-center">Visits By Country Per Day</h3>
		<!-- line chart - Multiple series -->
		<!-- You see a line for each country with each point corresponding to the number of visits for that day. -->
		<% @result = Visit.pluck('country').uniq.map{ |c| { name: c, data: @visits.where( country: c).group_by_day(:visited_at).count } } %>
		<%= line_chart @result%>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-6">
		<h3 class="text-center">Total Visits by Country</h3>
		<!-- pie chart will render with each slice representing the visits for that particular country -->
		<%= pie_chart @visits.group(:country).count %>	
	</div>
	<div class="col-xs-12 col-sm-12 col-md-6">
		<h3 class="text-center">Total Load time per day</h3>
		<!-- Area chart - with single series  -->
		<%= area_chart @visits.group_by_day(:visited_at).maximum(:load_time) %>
		<!-- area chart vith muliple series -->
		<%#= area_chart Visit.pluck('country').uniq.map{ |c| {name: c, data: @visits.where(country: c).group_by_day(:visited_at).maximum(:load_time)} }, descrete: true  %>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-6">
		<h3 class="text-center">Total Visits Per Country</h3>
		<%= column_chart @visits.group(:country).count %>	
	</div>
	<div class="col-xs-12 col-sm-12 col-md-6">
		<h3 class="text-center">Total Visits Per Country</h3>
		<!-- Area chart - with single series  -->
		<%= bar_chart @visits.group(:country).count %>
	</div>
</div>

app/views/homes/new.html.erb
<h1>Homes#new</h1>
<p>Find me in app/views/homes/new.html.erb</p>

app/views/homes/show.html.erb
<h1>Homes#show</h1>
<p>Find me in app/views/homes/show.html.erb</p>

app/views/homes/update.html.erb
<h1>Homes#update</h1>
<p>Find me in app/views/homes/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChartApplication</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%#= javascript_include_tag "path/to/highcharts.js", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/sales/_sale_by_month.html.erb
 <div class="col-sm-12 col-md-6">
 	<%= chart_by_tenpo_code(params[:tenpo_code]) %>
 </div>
 <% profit_data = get_profite_data(params[:tenpo_code]).sort %>
 <% sale_data = get_sale_data(params[:tenpo_code]).sort %>
 <div class="col-sm-12 col-md-6">
	 <table class="table table-condensed table-bordered">
	 	<thead>
	 		<tr>
	 			<th>Tenpo Code</th>
	 			<th>Month</th>
	 			<th>Rieki</th>
	 			<th>uriage</th>
	 			<th>%</th>
	 		</tr>
	 	</thead>
	 	<tbody>
	 		<% sale_data.zip(profit_data).each do |s,p|%>
	 		<tr>
	 			<td><%= params[:tenpo_code] %></td>
	 			<td><%= s[0] %></td>
	 			<td><%= p[1].round(2) %></td>
	 			<td><%= s[1].round(2) %></td>
	 			<td><%= (p[1]/s[1]*100).round(2) %></td>
	 		</tr>
	 		<% end %>
	 	</tbody>
	 </table>
 </div>

app/views/sales/index.html.erb
<div class="row">
	<div class="col-sm-12 col-md-6">
		<h3>売上総利益率推移</h3>
	</div>
</div>
<div class="row">
	<div class="col-sm-12 col-md-6">
		<div class="form-group">
		<%= select_tag :tenpo_code, options_for_select(Sale.all.map{ |t| [t.tenpo,t.tenpo]}.uniq.sort, params[:tenpo_code]), prompt: 'Select Tenpo Code', class: 'form-control', id: 'get_tenpo_code' %>
		</div>
	</div>
</div>
<div class="row" id="generate_chart">
	
</div>
<div class="row">
	<div class="col-sm-12 col-md-12">
		<div id="container"></div>
	</div>
</div>
<div class="row">
	<div class="col-sm-12 col-md-12">
		<div id="container1"></div>
	</div>
</div>

app/views/sales/search.js.erb
<% if params[:tenpo_code].present? %>
	$("#generate_chart").html("<%= escape_javascript(render(partial: 'sale_by_month'))%>")
<% end %>
$('#container').highcharts({
        chart: {
            zoomType: 'xy',
            style: {
                fontFamily: 'arial'
            }
        },
        title: {
            text: 'Title'
        },
        xAxis: [{
            categories: JSON.parse("[" + <%= @month %> + "]"),
            title: {
                text: 'Month',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            }
        }],
        yAxis: [{ // Primary yAxis
            labels: {
                format: '{value}',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            },
            title: {
                text: 'Sale of Month(%)',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            },
            opposite: true

        }, { // Secondary yAxis
            gridLineWidth: 0,
            title: {
                text: 'Profit of Month',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            },
            labels: {
                format: '{value}',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            }

        }],
        tooltip: {
            shared: true
        },
        legend: {
            //layout: 'vertical',
            align: 'center',
            //x: 80,
            margin: 500,
            layout: "horizontal",
            verticalAlign: 'top',
            //y: 90,
            floating: true,
            backgroundColor: (Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'
        },
        credits: {
      		enabled: false
  		},		
        series: [{
            name: 'Store Sale',
            type: 'column',
            yAxis: 1,
            data: JSON.parse("[" + <%= @month_profit %> + "]")
        }, 
        {
            name: 'Monthly Profite(%)',
            type: 'spline',
            data: JSON.parse("[" + <%= @sale_per %> + "]")
        }]
    });

$('#container1').highcharts({
        chart: {
            zoomType: 'xy',
            style: {
                fontFamily: 'arial'
            }
        },
        title: {
            text: 'Title'
        },
        xAxis: [{
            categories: JSON.parse("[" + <%= @month %> + "]"),
            title: {
                text: 'Month',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            }
        }],
        yAxis: [{ // Primary yAxis
            labels: {
                format: '{value}',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            },
            title: {
                text: 'Sale of Month(%)',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            },
            opposite: true

        }, { // Secondary yAxis
            gridLineWidth: 0,
            title: {
                text: 'Profit of Month',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            },
            labels: {
                format: '{value}',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            }

        },{ // Tertiary yAxis
            gridLineWidth: 0,
            title: {
                text: ''
            }
        }],
        tooltip: {
            shared: true
        },
        legend: {
            //layout: 'vertical',
            align: 'center',
            //x: 80,
            margin: 500,
            layout: "horizontal",
            verticalAlign: 'top',
            //y: 90,
            floating: true,
            backgroundColor: (Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'
        },
        credits: {
            enabled: false
        },      
        series: [{
            name: 'Store Sale',
            type: 'column',
            yAxis: 1,
            data: JSON.parse("[" + <%= @month_profit %> + "]")
        }, 
        {
            name: 'Monthly Profite(%)',
            type: 'spline',
            data: JSON.parse("[" + <%= @sale_per %> + "]")
        },{
            name: 'Total Profit(%)',
            type: 'spline',
            data: JSON.parse("[" + <%= @year_profit %> + "]"),
        }]
    });

/*$('#container1').highcharts({
        chart: {
            zoomType: 'xy'
        },
        title: {
            text: 'Average Monthly Weather Data for Tokyo'
        },
        subtitle: {
            text: 'Source: WorldClimate.com'
        },
        xAxis: [{
            categories: JSON.parse("[" + <%= @month %> + "]"),
            title: {
                text: 'Month',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            }
        }],
        yAxis: [{ // Primary yAxis
            labels: {
                format: '{value}',
                style: {
                    color: Highcharts.getOptions().colors[2]
                }
            },
            title: {
                text: 'Sale of Month(%)',
                style: {
                    color: Highcharts.getOptions().colors[2]
                }
            },
            opposite: true

        }, { // Secondary yAxis
            gridLineWidth: 0,
            title: {
                text: 'Profit of Month',
                style: {
                    color: Highcharts.getOptions().colors[0]
                }
            },
            labels: {
                format: '{value}',
                style: {
                    color: Highcharts.getOptions().colors[0]
                }
            }

        }, { // Tertiary yAxis
            gridLineWidth: 0,
        }],
        tooltip: {
            shared: true
        },
        legend: {
            //layout: 'vertical',
            align: 'center',
            //x: 80,
            margin: 500,
            layout: "horizontal",
            verticalAlign: 'top',
            //y: 90,
            floating: true,
            backgroundColor: (Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'
        },
        series: [{
            name: 'Rainfall',
            type: 'column',
            yAxis: 1,
            data: JSON.parse("[" + <%= @month_profit %> + "]")
        }, {
            name: 'Sea-Level Pressure',
            type: 'spline',
            yAxis: 2,
            data: JSON.parse("[" + <%= @sale_per %> + "]"),
            marker: {
                enabled: false
            },
            dashStyle: 'shortdot',

        }, {
            name: 'Temperature',
            type: 'spline',
            data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6],
        }]
    });*/

app/views/statistics/_competition_by_year.html.erb
<div class="col-xs-12 col-sm-12 col-md-6">
	<%= competition_by_year %>
</div>

app/views/statistics/_results_by_country.html.erb
<div class="col-xs-12 col-sm-12 col-md-6">
	<%= results_by_country %>
</div>

app/views/statistics/_sporters_by_age.html.erb
<div class="col-xs-12 col-sm-12 col-md-6">
	<%= sporters_by_age %>
</div>

app/views/statistics/_sporters_by_country.html.erb
<div class="col-xs-12 col-sm-12 col-md-6">
	<%= sporters_by_country %>
</div>

app/views/statistics/index.html.erb
<div class="row">
	<div class="col-sm-12">
		<%= link_to 'Other Graphs', homes_path, class: 'btn btn-danger btn-lg pull-right' %>
	</div>
</div>
<div class="row">
	<div class="form-group col-sm-6 col-md-6">
	<%= select_tag :chart_id, options_for_select([["Sporter by age",1],["Sporter by country",2],["Results by country",3],["Competition by year",4]]), prompt: 'Select Chart By category', class: 'form-control', id: 'get_chart' %>	
	</div>
</div>
<div class="row">
	<div id='set_chart'>
		
	</div>
</div>

app/views/statistics/search.js.erb
<% if params[:chart_id].present? %>
	<% if params[:chart_id] == '1' %>
		$("#set_chart").html("<%= escape_javascript(render(partial: 'sporters_by_age'))%>")
	<% elsif params[:chart_id] == '2' %>
		$("#set_chart").html("<%= escape_javascript(render(partial: 'sporters_by_country'))%>")
	<% elsif params[:chart_id] == '3' %>
		$("#set_chart").html("<%= escape_javascript(render(partial: 'results_by_country'))%>")
	<% elsif params[:chart_id] == '4' %>
		$("#set_chart").html("<%= escape_javascript(render(partial: 'competition_by_year'))%>")
	<% end %>
<% end %>